name: expense_manager
description: App to control expenses on credit and debit cards.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  # dependency injection and navigation
  flutter_modular: ^5.0.3

  # firebase
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.0

  # localization
  intl: ^0.17.0
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0

  # others
  flutter_svg: ^1.1.5
  email_validator: ^2.1.17
  faker: ^2.0.0
  result:
    git:
      url: https://github.com/tgdssm/result.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # tests
  mocktail: ^0.3.0
  firebase_auth_mocks: ^0.11.0
  fake_cloud_firestore: ^2.4.1+1
  google_sign_in_mocks: ^0.2.2

flutter:

  uses-material-design: true

  assets: 
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
