name: expense_manager
description: App to control expenses on credit and debit cards.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  # dependency injection and navigation
  flutter_modular: ^5.0.3

  # state manager
  get: ^4.6.5

  # tests
  mockito: ^5.3.0

  # firebase
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  google_sign_in: ^5.4.0

  # localization
  intl: ^0.17.0
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0

  # others
  either_dart: ^0.1.4
  dartz: ^0.10.1
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
